{% set size = size or 1 %}
{% set image_name = image_name or "^rally_cirros$" %}
{% set flavor_name = flavor_name or "rally" %}

{% set times = times or 1 %}
{% set concurrency = concurrency or 1 %}

  CinderVolumes.create_and_attach_volume:
    -
      args:
          size: {{ size }}
          image:
            name: "{{ image_name }}"
          flavor:
            name: "{{ flavor_name }}"
      runner:
        type: "constant"
        times: {{ times }}
        concurrency: {{ concurrency }}
      context: {}
