{% set flavor_name = flavor_name or "rally" %}
{% set image_name = image_name or "^rally_cirros$" %}
{% set times = times or 1 %}
{% set concurrency = concurrency or 1 %}


NovaServers.boot_and_delete_server:
  -
    args:
      flavor:
          name: "{{ flavor_name }}"
      image:
          name: "{{ image_name }}"
      force_delete: false
    runner:
      type: "constant"
      times: {{ times }}
      concurrency: {{ concurrency }}
    context: {}
